# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2018, Felipe Signorini
# This file is distributed under the same license as the Maestro Server - Cloud Inventory package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Maestro Server - Cloud Inventory 0.6\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-05-09 12:21+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../../troubleshooting.rst:2
msgid "Troubleshooting"
msgstr ""

#: ../../troubleshooting.rst:4
msgid "**1 - AWS was not able to validate the provided access credentials**"
msgstr ""

#: ../../troubleshooting.rst:6
msgid "I got this error using a valid AWS AK/SK the DescribeInstances operation consistently fails. The other BOTO3 calls work so it's something with this specific call."
msgstr ""

#: ../../troubleshooting.rst:15
msgid "Do the clock is right on your host?"
msgstr ""

#: ../../troubleshooting.rst:17
msgid "This message error normally happens when it has a wrong clock configuration, docker uses the host timezone. If yes can you try to use ntpdate on the host and then spin up again the discovery-maestro and discovery-maestro-workers https://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host"
msgstr ""

#: ../../troubleshooting.rst:21
msgid "Can be caused by a weird circumstance of running a local version at the same time as a cloud hosted one. Some services ran locally others on the cloud due to the way docker-compose was setup."
msgstr ""

#: ../../troubleshooting.rst:25
msgid "**2 - My client got Can't connect to Maestro Server**"
msgstr ""

#: ../../troubleshooting.rst:27
msgid "The server api are running?"
msgstr ""

#: ../../troubleshooting.rst:28
msgid "Your client service have the right configuration?"
msgstr ""

#: ../../troubleshooting.rst:42
msgid "**3 - Through Unauthorized error during the synchronization - Permission error**"
msgstr ""

#: ../../troubleshooting.rst:44
msgid "If through Unauthorized error, you need to grant ready only permission, as an example on AWS you should create IAM and grant full ready only permissions."
msgstr ""

#: ../../troubleshooting.rst:48
msgid "**4 - The warning status never change**"
msgstr ""

#: ../../troubleshooting.rst:50
msgid "Can be a RabbitMq issue or the Discovery workers weren't running, you can restart the rabbitmq and start the service discovery workers."
msgstr ""

#: ../../troubleshooting.rst:52
msgid "You always can check the service logs:"
msgstr ""
